package com.gotocompany.firehose.sink;

import com.gotocompany.firehose.exception.SinkTaskFailedException;
import com.gotocompany.firehose.message.Message;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.extern.slf4j.Slf4j;

import java.io.IOException;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.Callable;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.stream.Collectors;

/**
 * Pool of worker {@link Sink} instances that executes message-batch writes concurrently on a
 * shared {@link ExecutorService}.
 * <p>
 * Firehose can fan out the work of pushing batches across several identical sinks to increase
 * throughput. A caller submits a batch with {@link #submitTask(List)}, which borrows an idle sink
 * from an internal {@link BlockingQueue} and schedules a {@link SinkTask} on the executor,
 * returning a {@link Future} for the failed messages. Completed tasks are harvested with
 * {@link #fetchFinishedSinkTasks()}, which also returns each sink to the pool so it can be reused.
 * <p>
 * {@link #submitTask(List)} blocks for up to {@code pollTimeOutMillis} milliseconds waiting for a
 * free sink and returns {@code null} if none becomes available or the calling thread is
 * interrupted. {@link #close()} closes all managed sinks and shuts the executor down. The
 * constructor is generated by Lombok's {@code @AllArgsConstructor}.
 *
 * @see Sink
 */
@AllArgsConstructor
@Slf4j
public class SinkPool implements AutoCloseable {
    /** In-flight tasks paired with the sink executing them, tracked until they finish. */
    private final Set<SinkFuture> sinkFutures = new HashSet<>();
    /** Queue of currently idle sinks available to execute a batch. */
    private final BlockingQueue<Sink> workerSinks;
    /** Every sink managed by this pool, used to close them all on shutdown. */
    private final List<Sink> allSinks;
    /** Executor that runs the {@link SinkTask} instances. */
    private final ExecutorService executorService;
    /** Milliseconds to wait for an idle sink before {@link #submitTask(List)} gives up. */
    private final long pollTimeOutMillis;

    /**
     * Collects the tasks that have finished, returning their sinks to the pool.
     * <p>
     * Scans the in-flight tasks and, for each one whose {@link Future} is done, calls
     * {@code get()} to surface any execution error, puts the sink back on the idle queue, and
     * removes the task from the tracking set. The matching futures are returned so the caller can
     * read their results.
     *
     * @return the futures of the tasks that have completed since the last call
     * @throws SinkTaskFailedException if a finished task was interrupted or failed with an execution exception
     */
    public Set<Future<List<Message>>> fetchFinishedSinkTasks() {
        Set<SinkFuture> finished = sinkFutures.stream().filter(x -> {
            if (x.getFuture().isDone()) {
                try {
                    x.getFuture().get();
                    workerSinks.put(x.getSink());
                    return true;
                } catch (InterruptedException e) {
                    throw new SinkTaskFailedException(e);
                } catch (ExecutionException e) {
                    throw new SinkTaskFailedException(e.getCause());
                }
            }
            return false;
        }).collect(Collectors.toSet());
        sinkFutures.removeAll(finished);
        return finished.stream().map(SinkFuture::getFuture).collect(Collectors.toSet());
    }

    /**
     * Schedules a batch of messages to be written by an idle sink from the pool.
     * <p>
     * Waits up to {@code pollTimeOutMillis} milliseconds for a free sink. If one becomes available
     * it is removed from the idle queue, a {@link SinkTask} is submitted to the executor, and the
     * resulting future is tracked and returned. If no sink is available within the timeout, or the
     * thread is interrupted while waiting, {@code null} is returned and nothing is scheduled.
     *
     * @param messages the batch of messages to write
     * @return the {@link Future} of failed messages for the scheduled task, or {@code null} if no sink was available
     */
    public Future<List<Message>> submitTask(List<Message> messages) {
        try {
            Sink workerSink = workerSinks.poll(pollTimeOutMillis, TimeUnit.MILLISECONDS);
            if (workerSink == null) {
                return null;
            }
            Future<List<Message>> future = executorService.submit(new SinkTask(workerSink, messages));
            sinkFutures.add(new SinkFuture(future, workerSink));
            return future;
        } catch (InterruptedException e) {
            return null;
        }
    }

    /**
     * Closes every sink managed by the pool and shuts down the executor.
     * <p>
     * Each sink is closed in turn; a failure to close one sink is logged and does not prevent the
     * remaining sinks from being closed. After all sinks are closed the executor is shut down.
     */
    @Override
    public void close() {
        allSinks.forEach(sink -> {
            try {
                log.info("Closing sink");
                sink.close();
            } catch (IOException e) {
                log.error("Error happened while closing sink");
                e.printStackTrace();
            }
        });
        executorService.shutdown();
    }

    /**
     * Pairs an in-flight task's {@link Future} with the sink that is executing it.
     * <p>
     * Used internally to return the sink to the idle queue once its task completes. Lombok
     * generates the getters, setters, all-arguments constructor, {@code equals} and
     * {@code hashCode}.
     */
    @Data
    @AllArgsConstructor
    @EqualsAndHashCode
    protected static class SinkFuture {
        /** Future producing the list of messages the task failed to write. */
        private Future<List<Message>> future;
        /** Sink executing the task, to be returned to the pool when done. */
        private Sink sink;
    }

    /**
     * Sink Worker task.
     * It calls the pushMessage() and returns the response.
     */
    @AllArgsConstructor
    @EqualsAndHashCode
    protected static class SinkTask implements Callable<List<Message>> {
        /** Sink used to write the batch. */
        private final Sink sink;
        /** Batch of messages to be written. */
        private final List<Message> messages;

        /**
         * Writes the batch using the assigned sink.
         *
         * @return the messages that failed to be written
         * @throws Exception if the sink fails to push the batch
         */
        @Override
        public List<Message> call() throws Exception {
            return sink.pushMessage(messages);
        }
    }
}

