package com.gotocompany.firehose.sink.prometheus.builder;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A Prometheus label as a name-value pair.
 * <p>
 * Used when building Cortex time series; accessors, equality and constructors are generated by Lombok.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class PrometheusLabel {
    /** The label name. */
    private String name;
    /** The label value. */
    private String value;
}
