package com.gotocompany.firehose.sink.prometheus.builder;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * A Prometheus metric as a name and numeric value.
 * <p>
 * Used when building Cortex time series; accessors, equality and constructors are generated by Lombok.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class PrometheusMetric {
    /** The metric name. */
    private String name;
    /** The metric value. */
    private double value;
}
