package com.gotocompany.firehose.sinkdecorator;

import com.gotocompany.firehose.metrics.FirehoseInstrumentation;

import lombok.AllArgsConstructor;

/**
 * Sleeps the current thread for a requested duration, used to pause between retry attempts.
 *
 * <p>It is the low-level building block used by {@link ExponentialBackOffProvider}. If the sleep is
 * interrupted it records a non-fatal error through {@link FirehoseInstrumentation} rather than
 * propagating the {@link InterruptedException}. The constructor is generated by Lombok.
 */
@AllArgsConstructor
public class BackOff {

    /** Records a non-fatal error if the back-off sleep is interrupted. */
    private FirehoseInstrumentation firehoseInstrumentation;

    /**
     * Sleeps the calling thread for the given number of milliseconds.
     *
     * <p>If the thread is interrupted while sleeping, the interruption is captured as a non-fatal
     * error and the method returns normally instead of throwing.
     *
     * @param milliseconds the duration to sleep, in milliseconds
     */
    public void inMilliSeconds(long milliseconds) {
        try {
            Thread.sleep(milliseconds);
        } catch (InterruptedException e) {
            firehoseInstrumentation.captureNonFatalError("firehose_error_event", e, "Backoff thread sleep for {} milliseconds interrupted : {} {}",
                    milliseconds, e.getClass(), e.getMessage());
        }
    }
}
